set nocompatible
set nu
set bs=indent,eol,start
set ai
set nobackup
set ruler

let mapleader = ","
syntax enable
syntax on
set guifont=SourceCodePro\ SemiBold\ 13
colorscheme desert

set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
set fileencodings=utf-8,ucs-bom,cp936,gbk
set fileencoding=utf-8

set autoindent
set shiftwidth=4
set softtabstop=4
set smarttab
set tabstop=4
set showmatch

set history=1000
set smartcase
set hlsearch
set incsearch

set cursorline
set magic
set statusline=\ %<%F[%1*%M%*%n%R%H]%=\ %y\ %0(%{&fileformat}\ %{&encoding}\ %c:%l/%L%)\
set cmdheight=1

filetype on
filetype plugin on
filetype indent on

nmap <leader>w :w!<cr>
nmap <leader>q :q<cr>
nmap <leader>x :x<cr>

autocmd FileType python set expandtab
autocmd FileType python set wrap

